Resources:
  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: appointments
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ConformidadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQS_Conformidad
  EventBridgeToSQSRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "appointment"
        detail-type:
          - "AppointmentCompleted"
      Targets:
        - Arn: !GetAtt ConformidadQueue.Arn
          Id: "TargetSQS"
  SQSPE:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQS_PE
  SQSCL:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQS_CL
  SQSPESubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: arn:aws:sns:us-east-1:393157401981:AppoinmentsSNS
      Protocol: sqs
      Endpoint:
        Fn::GetAtt:
          - SQSPE
          - Arn
      FilterPolicy:
        countryISO:
          - "PE"
  SQSCLSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: arn:aws:sns:us-east-1:393157401981:AppoinmentsSNS
      Protocol: sqs
      Endpoint:
        Fn::GetAtt:
          - SQSCL
          - Arn
      FilterPolicy:
        countryISO:
          - "CL"
  AppointmentConfirmationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AppointmentConfirmationQueue
  EventBridgeToAppointmentConfirmationQueueRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "appointment"
        detail-type:
          - "AppointmentCompleted"
      Targets:
        - Arn: !GetAtt AppointmentConfirmationQueue.Arn
          Id: "TargetAppointmentConfirmationQueue"
  SqsPeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SqsPeQueue
  SqsClQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SqsClQueue
  SqsPeQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SqsPeQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt SqsPeQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref AppoinmentsSNS
  SqsClQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SqsClQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt SqsClQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref AppoinmentsSNS
  AppointmentConfirmationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AppointmentConfirmationQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt AppointmentConfirmationQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref EventBridgeToAppointmentConfirmationQueueRule
  SqsPeSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AppoinmentsSNS
      Protocol: sqs
      Endpoint: !GetAtt SqsPeQueue.Arn
      FilterPolicy:
        countryISO:
          - "PE"
  SqsClSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AppoinmentsSNS
      Protocol: sqs
      Endpoint: !GetAtt SqsClQueue.Arn
      FilterPolicy:
        countryISO:
          - "CL"
