Resources:
  # DynamoDB Table for Appointments
  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: appointments
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # SNS Topic for new appointments
  AppointmentsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AppointmentsSNSTopic

  # SQS Queue for Peru Appointments
  AppointmentQueuePE:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AppointmentQueuePE

  # SQS Queue for Chile Appointments
  AppointmentQueueCL:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AppointmentQueueCL

  # SQS Queue for Appointment Status Updates (from EventBridge)
  AppointmentConfirmationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AppointmentConfirmationQueue

  # SNS Subscription for PE Queue
  SnsToSqsSubscriptionPE:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AppointmentsSNSTopic
      Protocol: sqs
      Endpoint: !GetAtt AppointmentQueuePE.Arn
      FilterPolicy:
        countryISO:
          - "PE"

  # SNS Subscription for CL Queue
  SnsToSqsSubscriptionCL:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AppointmentsSNSTopic
      Protocol: sqs
      Endpoint: !GetAtt AppointmentQueueCL.Arn
      FilterPolicy:
        countryISO:
          - "CL"

  # SQS Policy for PE Queue to allow SNS
  SqsQueuePolicyPE:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AppointmentQueuePE
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt AppointmentQueuePE.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref AppointmentsSNSTopic

  # SQS Policy for CL Queue to allow SNS
  SqsQueuePolicyCL:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AppointmentQueueCL
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt AppointmentQueueCL.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref AppointmentsSNSTopic

  # EventBridge Rule to catch completion events
  EventBridgeCompletionRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "appointment"
        detail-type:
          - "AppointmentCompleted"
      Targets:
        - Arn: !GetAtt AppointmentConfirmationQueue.Arn
          Id: "AppointmentConfirmationTarget"

  # SQS Policy for Confirmation Queue to allow EventBridge
  EventBridgeSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AppointmentConfirmationQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt AppointmentConfirmationQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt EventBridgeCompletionRule.Arn
