service: appointment-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  appointment:
    handler: src/handlers/appointment.appointmentHandler
    events:
      - http:
          path: appointments
          method: post
  swagger:
    handler: src/handlers/swagger.swaggerHandler
    events:
      - http:
          path: swagger
          method: get

plugins:
  - serverless-offline
